name: CI-PROD

on:
  push:
    branches:
      - main
#  pull_request:
#    types:
#      - closed
#    branches:
#      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      ENVIRONMENT: ${{ steps.VIRER_ENV.outputs.ENVIRONMENT }}
      VERSION: ${{ steps.VIRER_ENV.outputs.VERSION }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Define version number as the branch merged "-" the current timestamp
        id: VIRER_ENV
        run: |
            declare -A BRANCH_MAP=(["develop"]="dev"
                       ["release"]="test"
                       ["acceptance"]="acceptance"
                       ["master"]="production"
                       ["main"]="production")
            
            # PR only : 
            # BRANCH_NAME="$( echo ${GITHUB_BASE_REF} | cut -d '/' -f1 )"
            
            # Commit only :
            BRANCH_NAME="$( echo ${GITHUB_REF} | cut -d '/' -f3 )"
            
            # Get env name from the branch name mapping
            echo "ENVIRONMENT="${BRANCH_MAP[${BRANCH_NAME}]} >> $GITHUB_OUTPUT
            VER=$(echo ${GITHUB_BASE_REF} | cut -d'/' -f2 )
            echo "VERSION="${BRANCH_MAP[${BRANCH_NAME}]}-${VER}-$(date +"%s") >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/scaps/${{ github.event.repository.name }}:${{ steps.VIRER_ENV.outputs.VERSION }},docker.io/scaps/${{ github.event.repository.name }}:latest
          build-args: |
              ENVIRONMENT=${{ steps.VIRER_ENV.outputs.ENVIRONMENT }}
  
